export const AttrMaps = {
  white: [
    'className',
    'style',
    'id',
    'title',
    'tabIndex',
    'role',
    'aria-label',
    'aria-hidden',
    'type',
    'value',
    'name',
    'placeholder',
    'checked',
    'disabled',
    'required',
    'readOnly',
    'src',
    'alt',
    'href',
    'target',
    'rel',
  ],
  warning: ['hidden', 'contentEditable', 'autoFocus', 'spellCheck'],
  danger: ['dangerouslySetInnerHTML', 'onScroll', 'onWheel'],
  denied: ['onload', 'srcdoc', 'formAction', 'formTarget'],
} as const
